# Generated by Django 5.2.5 on 2025-08-26 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_alter_track_name'),
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='trackid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='track.track'),
            preserve_default=False,
        ),
    ]
